node.id=node-2
server.host=0.0.0.0
server.port=8082
data.dir=/app/data/node2
cluster.peers=node-1=http://node1:8081,node-3=http://node3:8083
raft.election.timeout.min.ms=900
raft.election.timeout.max.ms=1600
raft.heartbeat.interval.ms=250
raft.client.commit.timeout.ms=5000
raft.replication.batch.size=128
