node.id=node-3
server.host=0.0.0.0
server.port=8083
data.dir=/app/data/node3
cluster.peers=node-1=http://node1:8081,node-2=http://node2:8082
raft.election.timeout.min.ms=900
raft.election.timeout.max.ms=1600
raft.heartbeat.interval.ms=250
raft.client.commit.timeout.ms=5000
raft.replication.batch.size=128
